### PR TITLE
feat: gateway connection

### PR DESCRIPTION
**Pull request by Wykerd**
Added WebSocket connection to gateway.
See **TODO:** comments for what still needs to be implemented.

### CODE REVIEW

**Comment by SirObby** [comment]
Are you saying this now makes bots connect to Discord?

**Comment by SirObby** [comment]
Hey there @Wykerd, this fails the checks. A problem with CMake and ur lib apparently.

**Comment by SirObby** [comment]
Once you can, pull from main on your fork or something, so I can rerun the new checks on the PR.

**Comment by Wykerd** [comment]
> Are you saying this now makes bots connect to Discord?

It connect to the gateway, I havent handled any of the events. You need to add a json library like yyjson to parse the messages before you can handle them.

**Comment by SirObby** [comment]
Does this work for you?

**Comment by SirObby** [comment]
I've ran this on my machine, and apparently the GitHub Checks do confirm, that this doesn't compile.
image

**Comment by Wykerd** [comment]
Yes. LibUV is added as a dependency, you need to install that first.

**Comment by Wykerd** [comment]
The package is called `libuv-dev` on ubuntu.

**Comment by SirObby** [comment]
Make it install the dependency in the workflows and add it into the Readme file.

**Comment by Wykerd** [comment]
I've added libuv as a subdirectory to cwire so it builds and statically links to it without needing it installed system wide.

All works now:
image

**Comment by SirObby** [comment]
Workflow failed for some reason.

**Comment by SirObby** [comment]
Since we don't yet have unit tests, Imma run this on my machine first.

**Comment by SirObby** [comment]
Or any actual tests at all.

**Comment by Wykerd** [comment]
Last commit should fix it for gcc.

**Comment by SirObby** [comment]
fyi, we have a Discord

**Comment by Wykerd** [comment]
Cool, send a link please :-)

**Comment by SirObby** [comment]
It's in the README.

**Comment by SirObby** [comment]
https://discord.gg/XEzUV5t3j9

**Pull request merged**
